//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_SaraKaminer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Category { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Title { get; set; }
        public string ArtDescription { get; set; }
        public string ArtDating { get; set; }
        public string ArtId { get; set; }
        public string Artist { get; set; }
        public string ArtistBirthDate { get; set; }
        public string ArtistDeathDate { get; set; }
        public string ArtistNationality { get; set; }
    }
}
